---
- name: config_samba | configuring samba
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nmbd
    - restart smbd
    - restart winbind
    - restart samba-ad-dc
  with_items:
    - 'etc/krb5.conf'
    - 'etc/samba/smb.conf'

- name: config_samba | checking if domain created
  stat:
    path: "/var/log/.samba_ad_created"
  register: samba_ad_created_check

- name: config_samba | configuring Active Directory
  shell: "samba-tool domain provision --realm={{ samba_ad_info['kerberos_realm']|upper }} --domain={{ samba_ad_info['netbios_domain_name']|upper }} --adminpass='{{ samba_ad_info['adminpass'] }}' --server-role='domain controller' --use-ntvfs"
  register: samba_ad_created
  when: >
        not samba_ad_created_check['stat']['exists'] and
        (samba_create_domain_controller is defined and
          samba_create_domain_controller) and
        samba_server_role == "active directory domain controller"

- name: config_samba | marking domain as created
  file:
    dest: "/var/log/.samba_ad_created"
    state: touch
  when: >
        samba_ad_created['changed'] and
        not samba_ad_created_check['stat']['exists']

- name: config_samba | unmask samba-ad-dc if this is a DC
  systemd:
    name: samba-ad-dc
    masked: no
  when: samba_server_role == "active directory domain controller"

- name: config_samba | checking if domain joined
  stat:
    path: "/var/log/.samba_ad_joined"
  register: samba_ad_joined_check

- name: config_samba | joining Active Directory domain
  shell: "samba-tool domain join {{ samba_ad_info['ad_dns_domain_name'] }} MEMBER --username='{{ samba_ad_info['netbios_domain_name']|upper }}\administrator' --password='{{ samba_ad_info['adminpass'] }}'"
  register: samba_ad_joined
  when: >
        not samba_ad_joined_check['stat']['exists'] and
        samba_server_role == "member server" and
        ansible_os_family == "Debian"

- name: config_samba | joining Active Directory domain
  shell: /usr/bin/net ads join -U 'Administrator'%{{ samba_ad_info['adminpass'] }}
  register: samba_ad_joined
  when: >
        not samba_ad_joined_check['stat']['exists'] and
        samba_server_role == "member server" and
        ansible_os_family == "RedHat"


- name: config_samba | marking domain as joined
  file:
    dest: "/var/log/.samba_ad_joined"
    state: touch
  when: >
        samba_ad_joined['changed'] and
        not samba_ad_joined_check['stat']['exists']

- name: Update nsswitch.conf
  lineinfile:
    regexp: "{{ item.regexp }}"
    line:   "{{ item.line   }}"
    dest: /etc/nsswitch.conf
  with_items:
    - { regexp: '^passwd:', line: 'passwd:		files winbind' }
    - { regexp: '^group:' , line: 'group:		files winbind' }
    - { regexp: '^shadow:', line: 'shadow:		files'         }
  when: >
        samba_server_role == "member server"

- name: Configure PAM authentication
  copy: src=common-auth dest=/etc/pam.d/common-auth force=no
  when: >
        samba_server_role == "member server"

- name: Configure home directory creation
  copy: src=common-session dest=/etc/pam.d/common-session force=no
  when: >
        samba_server_role == "member server"

